# This is a basic workflow to help you get started with Actions

name: Java CI with Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 # Checkout the code
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # Setup JAVA
        with:
         java-version: 1.8

  # uses: stCarolas/setup-maven@7060d72b50fbf2389a16d6f66a9c7d4d9ece5d36
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
         maven-version: 3.5.4
      - name: Build with Maven
        run: |
         mvn test
   



      
      - uses: nanasess/setup-chromedriver@master
      - run: chromedriver --url-base=/wd/hub &     

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: mvn -B package --file pom.xml test
    
     #Execute test
    #  - name: Build with MVN
    #    run: mvn clean test --file rdr-service/pom.xml
        
   
