# This is a basic workflow to help you get started with Actions

name: Selenium Java CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      ###
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
         java-version: '11'
         distribution: 'zulu'
      
  # uses: stCarolas/setup-maven@7060d72b50fbf2389a16d6f66a9c7d4d9ece5d36
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
         maven-version: 3.5.4
      
      - uses: nanasess/setup-chromedriver@master
      - run: chromedriver --url-base=/wd/hub &     

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
       #run: mvn test --file testng.xml
       # run: mvn compile -DsuiteXmlFile=testng.xml
        run: mvn -B package --file pom.xml test
    
     #Execute test
      - name: Build with MVN
        run: mvn clean test --file rdr-service/pom.xml
        
      - name: Test Reporter
      # You may pin to the exact commit or the version.
      # uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1
        uses: dorny/test-reporter@v1.5.0
     #   with:
      # Name or regex of artifact containing test results
      # Name of the check run
        # name: Test Run
        # path: "**/surefire-reports/TEST-*.xml"
        # reporter: java-junit 
